spring:
  data:
    mongodb:
      uri: mongodb+srv://261sainidhruv_db_user:dhruv639665@cluster0.iatef2z.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

  application:
    name: journalApplication

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 8080
  servlet:
    context-path: /journal
